/**
 * Responsive image manifest — GENERATED by _tools/gen-media-ts.mjs.
 * Do not edit by hand: run
 *   python _tools/build-media.py && node _tools/gen-media-ts.mjs
 * after changing the media pipeline.
 *
 * Every entry is a pre-rendered WebP variant produced from the venue's own
 * photographs published on the company's 2GIS card. `color` is the dominant
 * tone, used as the placeholder background so the layout never flashes white
 * and never shifts (CLS = 0).
 */

export type MediaVariant = { src: string; w: number; h: number };

export type MediaEntry = {
  color: string;
  wide?: MediaVariant[];
  tall?: MediaVariant[];
};

const v = (src: string, w: number, h: number): MediaVariant => ({ src, w, h });
const base = "/media/v2";

export const media = {
  hall: {
    color: "#44060d",
    wide: [
      v(`${base}/hall-wide-1600.webp`, 1600, 1000),
      v(`${base}/hall-wide-1100.webp`, 1100, 687),
      v(`${base}/hall-wide-700.webp`, 700, 437),
    ],
    tall: [
      v(`${base}/hall-tall-1200.webp`, 1200, 1601),
      v(`${base}/hall-tall-800.webp`, 800, 1067),
      v(`${base}/hall-tall-500.webp`, 500, 667),
    ],
  },
  stairs: {
    color: "#3f3733",
    wide: [
      v(`${base}/stairs-wide-1600.webp`, 1600, 1000),
      v(`${base}/stairs-wide-1100.webp`, 1100, 687),
      v(`${base}/stairs-wide-700.webp`, 700, 437),
    ],
    tall: [
      v(`${base}/stairs-tall-1200.webp`, 1200, 1600),
      v(`${base}/stairs-tall-800.webp`, 800, 1067),
      v(`${base}/stairs-tall-500.webp`, 500, 667),
    ],
  },
  mask: {
    color: "#2f2f44",
    wide: [
      v(`${base}/mask-wide-1600.webp`, 1600, 1000),
      v(`${base}/mask-wide-1100.webp`, 1100, 687),
      v(`${base}/mask-wide-700.webp`, 700, 437),
    ],
    tall: [
      v(`${base}/mask-tall-1200.webp`, 1200, 1600),
      v(`${base}/mask-tall-800.webp`, 800, 1067),
      v(`${base}/mask-tall-500.webp`, 500, 667),
    ],
  },
  posters: {
    color: "#3b3332",
    wide: [
      v(`${base}/posters-wide-1600.webp`, 1600, 1000),
      v(`${base}/posters-wide-1100.webp`, 1100, 688),
      v(`${base}/posters-wide-700.webp`, 700, 438),
    ],
    tall: [
      v(`${base}/posters-tall-1200.webp`, 1200, 1600),
      v(`${base}/posters-tall-800.webp`, 800, 1067),
      v(`${base}/posters-tall-500.webp`, 500, 667),
    ],
  },
  hero: {
    color: "#48060e",
    wide: [
      v(`${base}/hero-wide-1920.webp`, 1920, 1080),
      v(`${base}/hero-wide-1280.webp`, 1280, 720),
      v(`${base}/hero-wide-820.webp`, 820, 461),
    ],
    tall: [
      v(`${base}/hero-tall-1200.webp`, 1200, 1681),
      v(`${base}/hero-tall-760.webp`, 760, 1065),
    ],
  },
  about: {
    color: "#36302c",
    tall: [
      v(`${base}/about-tall-1100.webp`, 1100, 1375),
      v(`${base}/about-tall-700.webp`, 700, 875),
    ],
  },
  priceDom: {
    color: "#b18c69",
    tall: [
      v(`${base}/priceDom-1200.webp`, 1200, 2181),
      v(`${base}/priceDom-700.webp`, 700, 1272),
    ],
  },
  pricePilaA: {
    color: "#9f7e5f",
    tall: [
      v(`${base}/pricePilaA-1200.webp`, 1200, 2181),
      v(`${base}/pricePilaA-700.webp`, 700, 1272),
    ],
  },
  pricePilaB: {
    color: "#a28060",
    tall: [
      v(`${base}/pricePilaB-1200.webp`, 1200, 2181),
      v(`${base}/pricePilaB-700.webp`, 700, 1272),
    ],
  },
} satisfies Record<string, MediaEntry>;

export type MediaKey = keyof typeof media;
export type MediaKind = "wide" | "tall";

export function srcSet(entry: MediaEntry, kind: MediaKind): string {
  const list = entry[kind] ?? entry.wide ?? entry.tall ?? [];
  return list.map((i) => `${i.src} ${i.w}w`).join(", ");
}

export function fallback(entry: MediaEntry, kind: MediaKind): MediaVariant {
  const list = entry[kind] ?? entry.wide ?? entry.tall ?? [];
  return list[Math.min(1, list.length - 1)];
}
